spring:
  application:
    name: jwt
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt
    username: postgres
    password: R0ZUSNVuZQ=
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
    show_sql: true
    generate-ddl: true

server:
  port: 8000
